###
GET http://localhost:5006/games

###
GET http://localhost:5006/games/6

###
POST http://localhost:5006/games
Content-Type: application/json

{
    "name": "Spyro Reignited Trilogy",
    "genreId": 2,
    "price": 15.99,
    "release": "2020-12-10"
}

###
PUT http://localhost:5006/games/8
Content-Type: application/json

{
    "name": "Spyro 2",
    "genreId": 2,
    "price": 49.99,
    "releaseDate": "2020-12-10"
}

###
DELETE http://localhost:5006/games/9